### ISSUE TITLE
Discuss: Unable to Render Local Daruma File in vgg_web

### ISSUE THREAD

**Issue by hiiiroko** [verygoodgraphics/vgg_web#11]
Hello!

I'm having some issues trying to render local Daruma files using vgg_web, where the container is not successfully rendering the contents of the Daruma file as expected.

When I enter `/vgg_web/packages/react` and run the React framework for embedding the VGG Daruma design file into a web page, the page renders two sites similar to the old VGG official website using `VGGRender Component` and `useVGG Hook`, all going smoothly.

Then I entered `/vgg_web/packages/react/src/App.tsx`, downloaded the file from the `"src"` property link `"https://s3.vgg.cool/test/vgg.daruma"` in the parameter object of `useVGG Hook`, and placed it in the same directory as the aforementioned `App.tsx`. After that, I modified the `"src"` property to the local Daruma file in the same directory:

```
// /vgg_web/packages/react/src/App.tsx, line 9
function App() {
  const { canvasRef, vgg, isRendered } = useVGG({
    // src: "./vgg.daruma",
    src: "https://s3.vgg.cool/test/vgg.daruma",
    runtime: "https://s3.vgg.cool/test/runtime/latest",
  })
```
After this, the component using `useVGG` didn't render anything, and the browser console had an error:
```
Uncaught (in promise)
Error:
Failed to load Daruma file at g. render
(vgg-wasm.mjs: 340:13)
at async vgg.tsx:78:11
```
Modifying the `"src"` property of the `<VGGRender />` component to the local Daruma file path resulted in the same situation.

Then I tried using `import localDaruma from "./vgg.daruma"`, and then set the `<VGGRender />` component's `src={localDaruma}`, just like how image files are often handled in JSX, but this didn't work either. Meanwhile, VSCode showed:
```
Cannot find module './vgg.daruma' or its corresponding type declarations.ts(2307)
```
And the browser page popped up an error:
```
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. 
You may need to install appropriate plugins to handle the .daruma file format, or if it's an asset, add "**/*.daruma" to `assetsInclude` in your configuration.
/Users/cheems/Workbench/vgg_web-main/packages/react/src/vgg.daruma
```
Since the APIs for rendering VGG Daruma design files in other frameworks seem to be some kind of encapsulation of "new VGG({ ... })", I assume that performing the above actions in other frameworks under `/vgg_web/packages` would also encounter the same situation, and indeed this was the case after trying a few.

So, I'd like to ask where I went wrong with the above approach? How should I use vgg_web to render local Daruma files?

**Comment by harry75369** [comment]
You'd better not use local daruma files since there is no such a loader for .daruma files yet.

You should serve daruma files using a local web server, and pass the correct URL to the src parameter. One way is to use Vite's public assets directory: https://vitejs.dev/guide/assets.html#the-public-directory

**Comment by hiiiroko** [comment]
Got it, I'll try that, thanks a lot!
